Merged separate weekly-reports script into gtm as a command

diff --git a/gtm b/gtm
--- a/gtm
+++ b/gtm
@@ -89,9 +89,15 @@ gtm v$VERSION - git task/time manager (c) Alexey Alekhin
     `green steal`                 -- steal all time from another task (master by default) and move it to the current task
           [-i <issue>]       pick task by issue number
        or [-b <branch>]      pick task by branch name
+
+`bold 'Information commands'`:
     `green list`                  -- list all tasks with issue numbers and timers information
-    `green summary`               -- print summary of spent time by authors
     `green log`                   -- same as git-log but with human-format time notes
+    `green summary`               -- print summary of spent time by authors
+    `green report` [options]      -- print list of commits with time information and summary
+    `green weekly-report`         -- print reports grouped by weeks for a set of projects
+      [<first>] [<last>]     week diapason (just current week by default)
+      --projects <file>      file with projects mapping config (see help for details)
 
 `bold 'Commits related commands'`:
     `green undo`   [<number>]     -- (soft) reset given number of commits (1 by default) and return their time
@@ -112,7 +118,7 @@ gtm v$VERSION - git task/time manager (c) Alexey Alekhin
 function show_help {
     (( $# == 0 )) && echo "$general_help" && exit 0
     case $1 in
-        status|set|add|start|stop|amend|task|connect|info|switch|close|report|push)
+        status|set|add|start|stop|amend|task|connect|info|switch|close|report|weekly-report|push)
             gtm $1 --help
         ;;
         *)
@@ -220,6 +226,7 @@ function human_time() {
     fi
 }
 
+# given the number of week and optionally year, returns the date of it's week monday
 function monday() {
     local week=$1
     local year=${2:-$(date +%Y)}
@@ -228,6 +235,7 @@ function monday() {
     date -d "$year-01-01 -$((fst_week_day - 1)) day +$(($week - 1)) week" +%F
 }
 
+# the same as monay function +6 days
 function sunday() {
     date -d "$(monday $*) +6 day" +%F
 }
@@ -500,6 +508,86 @@ Shows list of commits which have time information. Optional flags are
         local pre="${total_line/_human_time_/$(human_time $total)}"
         echo "${pre/_time_/$(human_time $total --short)}"
     fi
+
+}
+
+function gtm_weekly_report() {
+    local help_msg="
+`bold Usage`: `blue 'gtm weekly-report'` `green '[<first week>] [<last week>]'` `green '--projects <file>'` `green '[<git log options>]'`
+
+Shows time reports (as `blue 'gtm report'`) grouped by weeks for a set of projects. You can set a configuration for the report with the following parameter:
+ `bold '*'` `green '--projects <file>'` - projects configuration file
+
+This projects mapping file is supposed to be a simple bash script, defining 
+ * `green prefix` string — path prefix of your local repositories;
+ * `green project` dispatch function — which takes project key and returns a string, that has project name (title) as the first row and the list of repositories as the following rows;
+ * `green projects` list — list of projects keys;
+
+This file can also redefine format options: `green header`, `green week_format`, `green project_format`, `green repo_format`, `green commit_format`, `green total_format`.
+"
+    case $1 in -h|--help) echo "$help_msg" && exit ;; esac
+
+
+    week=$(( $(date +%W) + 1 ))
+    [[ "$1" =~ [0-9]+ ]] && week=$1 && shift
+
+    until_week=$week
+    [[ "$1" =~ [0-9]+ ]] && until_week=$1 && shift
+
+    # defaults
+    header='# Weekly time records report \n\n'
+    week_format='## %s \n\n'
+    project_format='### %s \n\n'
+    repo_format='#. _repo_ \n'
+    commit_format='    + `[%h]` `_time_` — %s'
+    total_format='\n    In total: _human_time_\n'
+
+
+    # file with projects map and format options
+    file=""
+    [[ "$1" =~ --projects ]] && file=${2:?"Expected projects map file!"} && shift 2
+    source "$file"
+    (( $? != 0 )) && err "Failed to source '$file' script" ""
+
+
+    function list() {
+        local week=$1
+        shift
+        local mon=$(date -d "`monday $week`" +%d.%m.%Y)
+        local sun=$(date -d "`sunday $week`" +%d.%m.%Y)
+
+        printf "$week_format" "Week $week ($mon — $sun)"
+
+        for project_id in ${projects[@]}; do
+            local project_list=( $(project $project_id) )
+            local project=${project_list[0]//_/ }
+            local repos=${project_list[@]:1}
+            local repo_data=""
+
+            for repo in ${repos[@]}; do
+                cd "$prefix/$repo"
+                local commits=$(gtm report -f "$commit_format" -t "$total_format" -w $week "$@")
+                repo=${repo_format//_repo_/"$repo"}
+                [ "$commits" ] && repo_data="${repo_data}${repo}${commits}\n"
+            done
+
+            if [ "$repo_data" ]; then
+                printf "$project_format" "$project"
+                echo -e "$repo_data"
+            fi
+        done
+    }
+
+    local starting_point=$(pwd)
+
+    printf "$header"
+
+    until (( $week > $until_week )); do
+        list $week "$@"
+        week=$(( week + 1 ))
+    done
+
+    cd $starting_point
 
 }
 
@@ -1021,6 +1109,9 @@ case $subcommand in
     ;;
     report)
         gtm_report "$@"
+    ;;
+    weekly-report)
+        gtm_weekly_report "$@"
     ;;
     log)
         git log --color "$@" | sed "s/Time-spent: \([0-9]\+\)/gtm human-time \1/e" | less -R
